[orion]
env="development"
GRPCPort="9281"
HTTPPort="9282"
HystrixPort="9283"
PprofPort="9284"
ZipkinAddr="http://zipkin:9411/api/v1/spans"
rollbar-token=""
newrelicServiceName="Feed (dev)"
newrelicapikey=""

[feed]
key="value"

[feed.store.cassandra]
Hosts=["cassandra:9042"]

[feed.worker]
Host="rabbit:5672"
Queue="tasks"
Username="guest"
Password="guest"
