// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Feed.proto

/*
Package Feed_proto is a generated protocol buffer package.

It is generated from these files:
	Feed.proto

It has these top-level messages:
	StatusResponse
	Auth
	UserInfo
	ObjectInfo
	FeedItem
	FeedRequest
	FeedResponse
	RegisterRequest
	RegisterResponse
	LoginRequest
	LoginResponse
*/
package Feed_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Verb describes the verb of the activity
type Verb int32

const (
	// this verb ensures the activity is ignored
	Verb_IGNORE Verb = 0
	// this is used to display a generic feed type
	Verb_GENERIC Verb = 1
	Verb_LIKE    Verb = 2
	Verb_SHARE   Verb = 3
	Verb_POST    Verb = 4
)

var Verb_name = map[int32]string{
	0: "IGNORE",
	1: "GENERIC",
	2: "LIKE",
	3: "SHARE",
	4: "POST",
}
var Verb_value = map[string]int32{
	"IGNORE":  0,
	"GENERIC": 1,
	"LIKE":    2,
	"SHARE":   3,
	"POST":    4,
}

func (x Verb) String() string {
	return proto.EnumName(Verb_name, int32(x))
}
func (Verb) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// StatusResponse is the response sent by the server with every response
type StatusResponse struct {
	Code  int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error bool   `protobuf:"varint,2,opt,name=error" json:"error,omitempty"`
	Msg   string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StatusResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *StatusResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *StatusResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Auth container for uses to authenticate against APIs
// This data be provided by Acoount Login API
type Auth struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Auth) Reset()                    { *m = Auth{} }
func (m *Auth) String() string            { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()               {}
func (*Auth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Auth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// UserInfo describes a user
type UserInfo struct {
	UserName  string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Id        string `protobuf:"bytes,5,opt,name=id" json:"id,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserInfo) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ObjectInfo struct {
	// TODO should type be an enum ?
	// type of object
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// identifier of object
	Id string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *ObjectInfo) Reset()                    { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string            { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()               {}
func (*ObjectInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ObjectInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ObjectInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// FeedItem describes a single item in the feed
type FeedItem struct {
	// ID of this feed item
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// user who performed this activity
	Actor *UserInfo `protobuf:"bytes,2,opt,name=actor" json:"actor,omitempty"`
	// the type of activity
	Verb Verb `protobuf:"varint,3,opt,name=verb,enum=Feed_proto.Verb" json:"verb,omitempty"`
	// this field is used to describe how the activity should
	// be handled by older clients when a new activity is added
	CompatibilityVerb Verb `protobuf:"varint,4,opt,name=compatibility_verb,json=compatibilityVerb,enum=Feed_proto.Verb" json:"compatibility_verb,omitempty"`
	// object on which this activity occured
	Object string `protobuf:"bytes,5,opt,name=object" json:"object,omitempty"`
	// target of user for this activity
	Target *UserInfo `protobuf:"bytes,6,opt,name=target" json:"target,omitempty"`
}

func (m *FeedItem) Reset()                    { *m = FeedItem{} }
func (m *FeedItem) String() string            { return proto.CompactTextString(m) }
func (*FeedItem) ProtoMessage()               {}
func (*FeedItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FeedItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FeedItem) GetActor() *UserInfo {
	if m != nil {
		return m.Actor
	}
	return nil
}

func (m *FeedItem) GetVerb() Verb {
	if m != nil {
		return m.Verb
	}
	return Verb_IGNORE
}

func (m *FeedItem) GetCompatibilityVerb() Verb {
	if m != nil {
		return m.CompatibilityVerb
	}
	return Verb_IGNORE
}

func (m *FeedItem) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *FeedItem) GetTarget() *UserInfo {
	if m != nil {
		return m.Target
	}
	return nil
}

// FeedRequest contains request parameters to fetch feed
type FeedRequest struct {
	// Auth information for this request
	Auth *Auth `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	// number of items to fetch
	Count int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	// if userID is present we fetch feed OF that user
	UserID string `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
}

func (m *FeedRequest) Reset()                    { *m = FeedRequest{} }
func (m *FeedRequest) String() string            { return proto.CompactTextString(m) }
func (*FeedRequest) ProtoMessage()               {}
func (*FeedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FeedRequest) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *FeedRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FeedRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

// FeedResponse contains all fields needed to be fetched by the user
type FeedResponse struct {
	Status *StatusResponse `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Items  []*FeedItem     `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *FeedResponse) Reset()                    { *m = FeedResponse{} }
func (m *FeedResponse) String() string            { return proto.CompactTextString(m) }
func (*FeedResponse) ProtoMessage()               {}
func (*FeedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FeedResponse) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *FeedResponse) GetItems() []*FeedItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type RegisterRequest struct {
	UserName  string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Password  string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	FirstName string `protobuf:"bytes,5,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,6,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type RegisterResponse struct {
	Status *StatusResponse `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	User   *UserInfo       `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RegisterResponse) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RegisterResponse) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Status *StatusResponse `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Auth   *Auth           `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
	User   *UserInfo       `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *LoginResponse) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoginResponse) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *LoginResponse) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusResponse)(nil), "Feed_proto.StatusResponse")
	proto.RegisterType((*Auth)(nil), "Feed_proto.Auth")
	proto.RegisterType((*UserInfo)(nil), "Feed_proto.UserInfo")
	proto.RegisterType((*ObjectInfo)(nil), "Feed_proto.ObjectInfo")
	proto.RegisterType((*FeedItem)(nil), "Feed_proto.FeedItem")
	proto.RegisterType((*FeedRequest)(nil), "Feed_proto.FeedRequest")
	proto.RegisterType((*FeedResponse)(nil), "Feed_proto.FeedResponse")
	proto.RegisterType((*RegisterRequest)(nil), "Feed_proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "Feed_proto.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "Feed_proto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "Feed_proto.LoginResponse")
	proto.RegisterEnum("Feed_proto.Verb", Verb_name, Verb_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Feed service

type FeedClient interface {
	// Fetch fetchs the activity feed
	Fetch(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
}

type feedClient struct {
	cc *grpc.ClientConn
}

func NewFeedClient(cc *grpc.ClientConn) FeedClient {
	return &feedClient{cc}
}

func (c *feedClient) Fetch(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	out := new(FeedResponse)
	err := grpc.Invoke(ctx, "/Feed_proto.Feed/Fetch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Feed service

type FeedServer interface {
	// Fetch fetchs the activity feed
	Fetch(context.Context, *FeedRequest) (*FeedResponse, error)
}

func RegisterFeedServer(s *grpc.Server, srv FeedServer) {
	s.RegisterService(&_Feed_serviceDesc, srv)

}

func _Feed_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Feed_proto.Feed/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).Fetch(ctx, req.(*FeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Feed_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Feed_proto.Feed",
	HandlerType: (*FeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Feed_Fetch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Feed.proto",
}

// Client API for Account service

type AccountClient interface {
	// Register register's a user account in the system
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/Feed_proto.Account/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/Feed_proto.Account/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountServer interface {
	// Register register's a user account in the system
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)

}

func _Account_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Feed_proto.Account/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Feed_proto.Account/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Feed_proto.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Account_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Account_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Feed.proto",
}

func init() { proto.RegisterFile("Feed.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0x66, 0xba, 0xd3, 0xd2, 0x9e, 0x45, 0xac, 0x13, 0xa2, 0x75, 0xc1, 0x64, 0xd3, 0x78, 0xb1,
	0x21, 0x86, 0x98, 0xf5, 0xd6, 0x60, 0x88, 0x2c, 0xeb, 0x2a, 0x01, 0x33, 0xa8, 0xb7, 0xa4, 0xdb,
	0x1d, 0x96, 0x2a, 0x6d, 0xd7, 0x99, 0xa9, 0x86, 0x47, 0xf0, 0x56, 0xdf, 0xc0, 0x57, 0xf4, 0x05,
	0xcc, 0xfc, 0x14, 0xb6, 0x2b, 0xac, 0x17, 0xdc, 0xcd, 0xf9, 0x3f, 0xdf, 0x77, 0xbe, 0x01, 0x38,
	0x60, 0x6c, 0xb2, 0x33, 0xe3, 0xa5, 0x2c, 0x89, 0x7e, 0x9f, 0xea, 0x77, 0x7c, 0x08, 0xeb, 0x27,
	0x32, 0x91, 0x95, 0xa0, 0x4c, 0xcc, 0xca, 0x42, 0x30, 0x42, 0x00, 0xa7, 0xe5, 0x84, 0x45, 0xa8,
	0x8b, 0x7a, 0x2e, 0xd5, 0x6f, 0xb2, 0x01, 0x2e, 0xe3, 0xbc, 0xe4, 0x91, 0xd3, 0x45, 0x3d, 0x9f,
	0x1a, 0x83, 0x84, 0xd0, 0xca, 0xc5, 0x34, 0x6a, 0x75, 0x51, 0x2f, 0xa0, 0xea, 0x19, 0x6f, 0x01,
	0xde, 0xab, 0xe4, 0xb9, 0xca, 0x97, 0xe5, 0x17, 0x56, 0xe8, 0x26, 0x01, 0x35, 0x46, 0xfc, 0x03,
	0x81, 0xff, 0x51, 0x30, 0x3e, 0x2a, 0xce, 0x4a, 0xb2, 0x09, 0x41, 0x25, 0x18, 0x3f, 0x2d, 0x92,
	0x9c, 0xd9, 0x34, 0x5f, 0x39, 0x8e, 0x92, 0xdc, 0xcc, 0xcb, 0x93, 0xec, 0x42, 0xcf, 0x0b, 0xa8,
	0x31, 0xc8, 0x13, 0x80, 0xb3, 0x8c, 0x0b, 0x69, 0x6a, 0xcc, 0xd8, 0x40, 0x7b, 0x74, 0xd1, 0x26,
	0x04, 0x17, 0x49, 0x1d, 0xc5, 0xa6, 0xa3, 0x72, 0xe8, 0xe0, 0x3a, 0x38, 0xd9, 0x24, 0x72, 0xb5,
	0xd7, 0xc9, 0x26, 0xf1, 0x73, 0x80, 0xe3, 0xf1, 0x67, 0x96, 0x4a, 0xbd, 0x0c, 0x01, 0x2c, 0x2f,
	0x67, 0xf5, 0x1e, 0xfa, 0x6d, 0x2b, 0x9c, 0xab, 0x8a, 0x3f, 0x08, 0x7c, 0x45, 0xdc, 0x48, 0xb2,
	0xdc, 0x06, 0x51, 0x1d, 0x24, 0xdb, 0xe0, 0x26, 0xa9, 0xb4, 0x04, 0xb5, 0xfb, 0x1b, 0x3b, 0xd7,
	0x14, 0xef, 0xd4, 0x90, 0xa9, 0x49, 0x21, 0x4f, 0x01, 0x7f, 0x63, 0x7c, 0xac, 0x01, 0xac, 0xf7,
	0xc3, 0xf9, 0xd4, 0x4f, 0x8c, 0x8f, 0xa9, 0x8e, 0x92, 0x57, 0x40, 0xd2, 0x32, 0x9f, 0x25, 0x32,
	0x1b, 0x67, 0x17, 0x99, 0xbc, 0x3c, 0xd5, 0x35, 0xf8, 0x96, 0x9a, 0x07, 0x8d, 0x5c, 0xe5, 0x22,
	0x0f, 0xc1, 0x2b, 0x35, 0x42, 0x8b, 0xda, 0x5a, 0xe4, 0x19, 0x78, 0x32, 0xe1, 0x53, 0x26, 0x23,
	0x6f, 0xc9, 0xae, 0x36, 0x27, 0x4e, 0xa0, 0xad, 0xc2, 0x94, 0x7d, 0xad, 0x98, 0x90, 0x6a, 0xf7,
	0xa4, 0x92, 0xe7, 0x1a, 0x79, 0xbb, 0xb9, 0x87, 0x3a, 0x3c, 0xd5, 0x51, 0x75, 0xbe, 0xb4, 0xac,
	0x0a, 0xa9, 0xd9, 0x70, 0xa9, 0x31, 0xd4, 0x42, 0xea, 0xc0, 0xa3, 0x7d, 0x7b, 0x3a, 0x6b, 0xc5,
	0x05, 0xac, 0x99, 0x11, 0x56, 0x80, 0x7d, 0xf0, 0x84, 0x96, 0xa4, 0x9d, 0xd2, 0x99, 0x9f, 0xd2,
	0x14, 0x2b, 0xb5, 0x99, 0x8a, 0xff, 0x4c, 0xb2, 0x5c, 0x44, 0x4e, 0xb7, 0xb5, 0x88, 0xa9, 0x3e,
	0x1a, 0x35, 0x29, 0xf1, 0x6f, 0x04, 0xf7, 0x29, 0x9b, 0x66, 0x42, 0x32, 0x5e, 0xe3, 0x6a, 0xa8,
	0xd1, 0x59, 0x50, 0x63, 0x07, 0xfc, 0x59, 0x22, 0xc4, 0xf7, 0x92, 0x4f, 0xec, 0xea, 0x57, 0xf6,
	0xb5, 0x52, 0xf1, 0xed, 0x4a, 0x75, 0x97, 0x2a, 0xd5, 0x6b, 0x2a, 0xf5, 0x2d, 0xf6, 0x51, 0xe8,
	0xc4, 0x33, 0x08, 0xaf, 0x77, 0xbc, 0x03, 0x31, 0x3d, 0xc0, 0x0a, 0xc7, 0x52, 0x5d, 0xea, 0x8c,
	0x78, 0x08, 0x6b, 0x87, 0xe5, 0x34, 0x2b, 0x6e, 0xa4, 0x04, 0x2d, 0xa1, 0xc4, 0x69, 0x52, 0x12,
	0xff, 0x42, 0x70, 0xcf, 0x76, 0xba, 0xc3, 0xe2, 0xb5, 0xd2, 0x9c, 0xa5, 0x4a, 0xab, 0xe1, 0xb5,
	0xfe, 0x07, 0x6f, 0x7b, 0x17, 0xb0, 0xfe, 0x16, 0x00, 0xde, 0x68, 0x78, 0x74, 0x4c, 0x07, 0xe1,
	0x0a, 0x69, 0xc3, 0xea, 0x70, 0x70, 0x34, 0xa0, 0xa3, 0xd7, 0x21, 0x22, 0x3e, 0xe0, 0xc3, 0xd1,
	0xbb, 0x41, 0xe8, 0x90, 0x00, 0xdc, 0x93, 0x37, 0x7b, 0x74, 0x10, 0xb6, 0x94, 0xf3, 0xfd, 0xf1,
	0xc9, 0x87, 0x10, 0xf7, 0xf7, 0x01, 0xab, 0xe6, 0xe4, 0x25, 0xb8, 0x07, 0x4c, 0xa6, 0xe7, 0xe4,
	0xd1, 0xa2, 0xc6, 0x2c, 0x71, 0x9d, 0xe8, 0xdf, 0x80, 0xc1, 0x16, 0xaf, 0xf4, 0x7f, 0x22, 0x58,
	0xdd, 0x4b, 0xcd, 0x7f, 0x18, 0x82, 0x5f, 0x9f, 0x98, 0x6c, 0xce, 0xd7, 0x2c, 0x88, 0xb3, 0xb3,
	0x75, 0x73, 0xb0, 0x6e, 0x4a, 0x76, 0xc1, 0xd5, 0x7c, 0x93, 0xc6, 0xe4, 0xf9, 0x63, 0x76, 0x1e,
	0xdf, 0x10, 0xa9, 0xeb, 0xc7, 0x9e, 0x76, 0xbf, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x81, 0x88,
	0xd7, 0x2c, 0x24, 0x06, 0x00, 0x00,
}
