// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: Feed.proto

package Feed_proto

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

// Encoders

// Handlers

// Decoders

//Streams

// RegisterFeedOrionServer registers Feed to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterFeedOrionServer(sf interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&_Feed_serviceDesc, sf)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterFeedDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "Feed", encoder)
}

// DefaultDecoder
func RegisterFeedDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "Feed", decoder)
}
// Encoders

// Handlers

// Decoders

//Streams

// RegisterAccountOrionServer registers Account to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterAccountOrionServer(sf interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&_Account_serviceDesc, sf)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterAccountDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "Account", encoder)
}

// DefaultDecoder
func RegisterAccountDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "Account", decoder)
}

