// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Feed.proto

/*
Package Feed_proto is a generated protocol buffer package.

It is generated from these files:
	Feed.proto

It has these top-level messages:
	EchoRequest
	EchoResponse
	UpperRequest
	UpperResponse
*/
package Feed_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type EchoResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EchoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UpperRequest struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *UpperRequest) Reset()                    { *m = UpperRequest{} }
func (m *UpperRequest) String() string            { return proto.CompactTextString(m) }
func (*UpperRequest) ProtoMessage()               {}
func (*UpperRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpperRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UpperResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *UpperResponse) Reset()                    { *m = UpperResponse{} }
func (m *UpperResponse) String() string            { return proto.CompactTextString(m) }
func (*UpperResponse) ProtoMessage()               {}
func (*UpperResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpperResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "Feed_proto.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "Feed_proto.EchoResponse")
	proto.RegisterType((*UpperRequest)(nil), "Feed_proto.UpperRequest")
	proto.RegisterType((*UpperResponse)(nil), "Feed_proto.UpperResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Feed service

type FeedClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// ORION:URL: GET/POST/OPTIONS /api/1.0/upper/{msg}
	Upper(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperResponse, error)
	// ORION:URL: POST/PUT
	UpperProxy(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperResponse, error)
}

type feedClient struct {
	cc *grpc.ClientConn
}

func NewFeedClient(cc *grpc.ClientConn) FeedClient {
	return &feedClient{cc}
}

func (c *feedClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/Feed_proto.Feed/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) Upper(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperResponse, error) {
	out := new(UpperResponse)
	err := grpc.Invoke(ctx, "/Feed_proto.Feed/Upper", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) UpperProxy(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperResponse, error) {
	out := new(UpperResponse)
	err := grpc.Invoke(ctx, "/Feed_proto.Feed/UpperProxy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Feed service

type FeedServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// ORION:URL: GET/POST/OPTIONS /api/1.0/upper/{msg}
	Upper(context.Context, *UpperRequest) (*UpperResponse, error)
	// ORION:URL: POST/PUT
	UpperProxy(context.Context, *UpperRequest) (*UpperResponse, error)
}

func RegisterFeedServer(s *grpc.Server, srv FeedServer) {
	s.RegisterService(&_Feed_serviceDesc, srv)

}

func _Feed_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Feed_proto.Feed/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_Upper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).Upper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Feed_proto.Feed/Upper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).Upper(ctx, req.(*UpperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_UpperProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).UpperProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Feed_proto.Feed/UpperProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).UpperProxy(ctx, req.(*UpperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Feed_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Feed_proto.Feed",
	HandlerType: (*FeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Feed_Echo_Handler,
		},
		{
			MethodName: "Upper",
			Handler:    _Feed_Upper_Handler,
		},
		{
			MethodName: "UpperProxy",
			Handler:    _Feed_UpperProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Feed.proto",
}

func init() { proto.RegisterFile("Feed.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x72, 0x4b, 0x4d, 0x4d,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x02, 0xb3, 0xe3, 0xc1, 0x6c, 0x25, 0x79, 0x2e, 0x6e,
	0xd7, 0xe4, 0x8c, 0xfc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x01, 0x2e, 0xe6, 0xdc,
	0xe2, 0x74, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x49, 0x81, 0x8b, 0x07, 0xa2,
	0xa0, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0xbb, 0x8a, 0xd0, 0x82, 0x82, 0xd4, 0x22, 0xdc, 0x66,
	0x28, 0x72, 0xf1, 0x42, 0x55, 0xe0, 0x32, 0xc4, 0xe8, 0x04, 0x23, 0x17, 0x0b, 0xc8, 0x59, 0x42,
	0xd6, 0x5c, 0x2c, 0x20, 0xfb, 0x84, 0xc4, 0xf5, 0x10, 0xae, 0xd4, 0x43, 0x72, 0xa2, 0x94, 0x04,
	0xa6, 0x04, 0xc4, 0x54, 0x25, 0x06, 0x21, 0x3b, 0x2e, 0x56, 0xb0, 0x45, 0x42, 0x28, 0x8a, 0x90,
	0x5d, 0x27, 0x25, 0x89, 0x45, 0x06, 0xae, 0xdf, 0x99, 0x8b, 0x0b, 0x2c, 0x14, 0x50, 0x94, 0x5f,
	0x51, 0x49, 0xa6, 0x21, 0x49, 0x6c, 0x60, 0x61, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70,
	0xb4, 0xee, 0x75, 0x73, 0x01, 0x00, 0x00,
}
