// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

/*
Package cache_proto is a generated protocol buffer package.

It is generated from these files:
	cache.proto

It has these top-level messages:
	UserInfo
	FeedInfo
*/
package cache_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName" json:"lastName,omitempty"`
	UserName  string `protobuf:"bytes,4,opt,name=userName" json:"userName,omitempty"`
	Email     string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfo) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserInfo) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type FeedInfo struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Actor  string `protobuf:"bytes,2,opt,name=actor" json:"actor,omitempty"`
	Verb   string `protobuf:"bytes,3,opt,name=verb" json:"verb,omitempty"`
	CVerb  string `protobuf:"bytes,4,opt,name=cVerb" json:"cVerb,omitempty"`
	Object string `protobuf:"bytes,5,opt,name=object" json:"object,omitempty"`
	Target string `protobuf:"bytes,6,opt,name=target" json:"target,omitempty"`
	Ts     int64  `protobuf:"varint,7,opt,name=ts" json:"ts,omitempty"`
}

func (m *FeedInfo) Reset()                    { *m = FeedInfo{} }
func (m *FeedInfo) String() string            { return proto.CompactTextString(m) }
func (*FeedInfo) ProtoMessage()               {}
func (*FeedInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FeedInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FeedInfo) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

func (m *FeedInfo) GetVerb() string {
	if m != nil {
		return m.Verb
	}
	return ""
}

func (m *FeedInfo) GetCVerb() string {
	if m != nil {
		return m.CVerb
	}
	return ""
}

func (m *FeedInfo) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *FeedInfo) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *FeedInfo) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "cache_proto.UserInfo")
	proto.RegisterType((*FeedInfo)(nil), "cache_proto.FeedInfo")
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0x76, 0x5b, 0xbb, 0x23, 0x78, 0x18, 0x16, 0x09, 0xe2, 0x61, 0xd9, 0x53, 0x4f,
	0x5e, 0x7c, 0x07, 0xc1, 0x8b, 0x87, 0x82, 0x5e, 0x25, 0x4d, 0xa7, 0x1a, 0x69, 0x8d, 0x24, 0xa3,
	0x8f, 0xe0, 0x43, 0xf8, 0xb4, 0x92, 0x4c, 0xd4, 0x8b, 0xb7, 0x7e, 0xdf, 0x57, 0xf8, 0x87, 0xc0,
	0xa9, 0xb3, 0xee, 0x99, 0xae, 0xde, 0x62, 0xe0, 0x80, 0x02, 0x8f, 0x05, 0x8e, 0x9f, 0x0a, 0xba,
	0xfb, 0x44, 0xf1, 0xf6, 0x75, 0x0e, 0x78, 0x06, 0xda, 0x4f, 0x46, 0x1d, 0x54, 0xbf, 0x1b, 0xb4,
	0x9f, 0xf0, 0x12, 0x76, 0xb3, 0x8f, 0x89, 0xef, 0xec, 0x4a, 0x46, 0x17, 0xfd, 0x27, 0xf0, 0x02,
	0xba, 0xc5, 0xd6, 0xb8, 0x29, 0xf1, 0x97, 0x73, 0x7b, 0x4f, 0x14, 0x4b, 0xdb, 0x4a, 0xfb, 0x61,
	0xdc, 0x43, 0x43, 0xab, 0xf5, 0x8b, 0x69, 0x4a, 0x10, 0x38, 0x7e, 0x29, 0xe8, 0x6e, 0x88, 0xa6,
	0x7f, 0x0f, 0xd9, 0x43, 0x63, 0x1d, 0x87, 0x58, 0x8f, 0x10, 0x40, 0x84, 0xed, 0x07, 0xc5, 0xb1,
	0x8e, 0x97, 0xef, 0xfc, 0xa7, 0x7b, 0xc8, 0x52, 0x56, 0x05, 0xf0, 0x1c, 0xda, 0x30, 0xbe, 0x90,
	0xe3, 0xba, 0x59, 0x29, 0x7b, 0xb6, 0xf1, 0x89, 0xd8, 0xb4, 0xe2, 0x85, 0xf2, 0x3e, 0x27, 0x73,
	0x72, 0x50, 0xfd, 0x66, 0xd0, 0x9c, 0xc6, 0xb6, 0x3c, 0xd6, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfc, 0x13, 0x93, 0xed, 0x48, 0x01, 0x00, 0x00,
}
